# Generated by Django 3.2.6 on 2021-09-01 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='receiver',
            new_name='recipient',
        ),
        migrations.AddField(
            model_name='message',
            name='title',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='id',
            field=models.SlugField(max_length=15, primary_key=True, serialize=False),
        ),
    ]
